version: "3"

services:
  web:
    build: ./php
    ports:
     - 80:80
    volumes:
     - ./../palpit:/var/www/html
    networks:
      - palpit
    links:
      - database
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - 3360:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - palpit

networks:
  palpit:
    driver: bridge